/* tslint:disable */
/* eslint-disable */
/**
 * DRC API document
 * This is a Dog Rescue Center
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: tdbao1@cmcglobal.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

